In [1]:
import numpy as np

v1 = np.array([4,2,6,1])
v2 = np.random.rand(4)

print(v1, "\n", v2)

[4 2 6 1] 
 [0.95022357 0.52335828 0.8545647  0.376463  ]


In [2]:
w = [x**2 for x in v1]

In [3]:
w

[16, 4, 36, 1]

In [4]:
v1.shape

(4,)

In [5]:
n, = v1.shape
print(n)
v3 = np.zeros(n)
print(v3)
for j in range(n):
    v3[j] = v1[j]**2
print(v3)
v4 = v1**2
print(v4)

4
[0. 0. 0. 0.]
[16.  4. 36.  1.]
[16  4 36  1]
