In [2]:
import numpy as np

u = np.array([1,2,3,4])
v = np.array([2,3,0,1])

print(u.shape, v.shape)
print(u, v)

(4,) (4,)
[1 2 3 4] [2 3 0 1]


In [3]:
print(u*v, u.dot(v))

[2 6 0 4] 12


In [4]:
cu = u.reshape(4,1)
print(cu.shape, "\n")
print(cu)

(4, 1) 

[[1]
 [2]
 [3]
 [4]]


In [5]:
print(cu * v)

[[ 2  3  0  1]
 [ 4  6  0  2]
 [ 6  9  0  3]
 [ 8 12  0  4]]


In [6]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[2, 1],[-2, 3]])

print(m1, "\n\n", m2)

[[1 2]
 [3 4]] 

 [[ 2  1]
 [-2  3]]


In [7]:
print(m1*m2, "\n\n", m1.dot(m2))

[[ 2  2]
 [-6 12]] 

 [[-2  7]
 [-2 15]]


In [8]:
a = np.array([
    [1,0,0,0],
    [0,1,1,0],
    [0,0,1,2]
])

In [9]:
print(a.dot(u), "\n")
print(a.dot(cu))

[ 1  5 11] 

[[ 1]
 [ 5]
 [11]]


In [10]:
b = np.array([ [3,1], [2,2], [1,3], [1,11]])
print(a, "\n\n\n", b)

[[1 0 0 0]
 [0 1 1 0]
 [0 0 1 2]] 


 [[ 3  1]
 [ 2  2]
 [ 1  3]
 [ 1 11]]


In [11]:
print(a.dot(b))

[[ 3  1]
 [ 3  5]
 [ 3 25]]


In [12]:
a.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 2]])

In [13]:
print(a.shape, a.T.shape)

(3, 4) (4, 3)


In [14]:
print(a)

[[1 0 0 0]
 [0 1 1 0]
 [0 0 1 2]]


In [15]:
u.dot(a.T)

array([ 1,  5, 11])

In [16]:
(m,n) = a.shape
c = np.zeros((m,n), "int32")
print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
for i in range(m):
    for j in range(n):
        c[i,j] = a[i,j]*2

print(c)

[[2 0 0 0]
 [0 2 2 0]
 [0 0 2 4]]


In [18]:
print(a*2)

[[2 0 0 0]
 [0 2 2 0]
 [0 0 2 4]]


In [19]:
def multiply_matrix_by_vector(m, v):
    R,C = m.shape
    n, = v.shape

    print("\nR and C are ", R, C)

    if C!=n:
        print("\n array and vector shapes not matching\n")
        return None

    u = np.zeros((R,C), "int32")

    for i in range(R):
        for j in range(C):
            u[i,j] = m[i,j]*v[j]

    return u

print(multiply_matrix_by_vector(a, np.array([3, 2, 1, 3])))


R and C are  3 4
[[3 0 0 0]
 [0 2 1 0]
 [0 0 1 6]]


In [23]:
def multiply_matrices(a, b):
    R, C1 = a.shape
    R1, C = b.shape

    if C1 != R1:
        print("\nArray shapes not matching for multiplication\n")
        return None

    c = np.zeros((R, C))

    for i in range(R):
        for j in range(C):
            for k in range(C1):
                c[i, j] += a[i, k] * b[k, j]
    return c

print(multiply_matrices(a, b))

[[ 3.  1.]
 [ 3.  5.]
 [ 3. 25.]]


In [21]:
def f(x, matrices):
    y = x
    for m in matrices:
        y = np.dot(y, m)

    return  y

x = np.array([1, 2, 3])
matrices = [np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]), np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])]

print(f(x, matrices))

[60 72 84]
